### ISSUE TITLE
anaconda upload failing with 'file does not exist'

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/lal-feedstock#8]
`anaconda upload` from both CircleCI and TravisCI is failing for the new release with errors like this [[ref](https://circleci.com/gh/conda-forge/lal-feedstock/22), [ref](https://travis-ci.org/conda-forge/lal-feedstock/builds/433379714)]:

```
[ERROR] File "/home/conda/feedstock_root/build_artifacts/linux-64/lal-6.19.0-hee24be8_0.tar.bz2" does not exist
Traceback (most recent call last):
  File "/opt/conda/bin/upload_package", line 11, in <module>
    sys.exit(upload_package())
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/build_utils.py", line 82, in upload_package
    upload_or_check(recipe_root, owner, channel, [config_file])
  File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 135, in upload_or_check
    upload(token_fn, path, owner, channel)
  File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 65, in upload
    env=os.environ)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', '/tmp/tmptxtgcqgp/binstar.token', 'upload', '/home/conda/feedstock_root/build_artifacts/linux-64/lal-6.19.0-hee24be8_0.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
Exited with code 1
```

cc: @conda-forge/core - help is greatly appreciated.

**Comment by scopatz** [comment]
In these cases, usually a restart is all that is needed.

**Comment by duncanmmacleod** [comment]
@scopatz, I've repeated these CI jobs many times today, always to the same failure.

**Comment by scopatz** [comment]
Ahh, right, I recall this issue from a few weeks ago.  I think you may need to rerender

**Comment by duncanmmacleod** [comment]
thanks @scopatz, see #9; I don't understand how this will solve the issue, but then again, understanding is not required if it works.

**Comment by isuruf** [comment]
This recipe is a mess. Can you describe what you were trying to do with outputs here? Why are there python dependencies in the outer build requirements block?

**Comment by duncanmmacleod** [comment]
@isuruf, the tarball supports building a C library with SWIG bindings for python and octave. This recipe is designed to build the package with python bindings, and then separate out the C and python layers into separate `outputs`, we might add `octave` at a later date.

There are python dependencies in the outer `host` requirements block because `make check` requires those packages to be installed.

I would be happy to receive any and all advise on how to clean up the recipe. Thanks.

**Comment by isuruf** [comment]
How are the python bindings built? Is it into the same C shared library? Or separate shared library?

**Comment by duncanmmacleod** [comment]
@isuruf, if I understand you, `SWIG` builds the python bindings into a separate shared library. There are also pure-python libraries on top of that as well.

**Comment by skymoo** [comment]
@duncanmmacleod is right, at the moment a full `./configure && make && make install` is needed to build the bindings for each Python version. It's a problem and it is on the TODO list to address, however our SWIG expert is swamped with other things and doesn't know when he'll be able to get to this.
